const FORM_OPERATION_UPDATE = 'update'
const FORM_OPERATION_INSERT = 'insert'
const USER_ROLE_ADMINISTRATOR = 'administrador'
const USER_ROLE_EMPLOYEE = 'funcionario'
const USER_MESSAGES_6_SECONDS_TIMER = 6000

const TITLE_FORM_OPERATION_UPDATE = 'Alterar dados do Usuário'
const TITLE_FORM_OPERATION_INSERT = 'Incluir Usuário'

const RETURN_MESSAGE_OPERATION_UPDATE = 'Usuário alterado com sucesso...'
const RETURN_MESSAGE_OPERATION_INSERT = 'Usuário incluído com sucesso...'
  
export { 
    FORM_OPERATION_UPDATE, 
    FORM_OPERATION_INSERT, 
    USER_ROLE_ADMINISTRATOR, 
    USER_ROLE_EMPLOYEE, 
    TITLE_FORM_OPERATION_UPDATE, 
    TITLE_FORM_OPERATION_INSERT,
    USER_MESSAGES_6_SECONDS_TIMER,
    RETURN_MESSAGE_OPERATION_UPDATE,
    RETURN_MESSAGE_OPERATION_INSERT
 }